### ISSUE TITLE
Test doesn't use the NPU, change to rknn-benchmark

### ISSUE THREAD

**Issue by Pelochus** [Pelochus/ezrknn-toolkit2#2]
The test in the README doesn't use the NPU, change to anything that actually uses it.

**Comment by Pelochus** [comment]
Running rknn-benchmark solves the issue. Seems like test.py for rasnet18 didn't use the NPU (or uses it very lightly). Move one `.rknn` file (for example, from `rknn-toolkit-lite2/examples/resnet18` folder) to the `rknpu2/examples/rknn_benchmark/install` to use rknn-benchmark.
See this screenshot for actually testing if the NPU is being used:

![image](https://github.com/Pelochus/ezrknn-toolkit2/assets/49835792/df704d23-4ae5-4300-ab2a-51927b369c89)

**Comment by alexxony** [comment]
Should I install libraries each ??


![Image](https://github.com/user-attachments/assets/fe3db672-7864-4bcf-9ea4-49ab8063a6dc)

**Comment by Pelochus** [comment]
> Should I install libraries each ??
> 
> ![Image](https://github.com/user-attachments/assets/fe3db672-7864-4bcf-9ea4-49ab8063a6dc)

Yes, install that library
